### ISSUE TITLE
Input as a nested array structure?

### ISSUE THREAD

**Issue by spekulatius** [romanzipp/Laravel-SEO#21]
Hello @romanzipp 

Your SEO package looks great, well thought out! Thank you for maintaining it!

I'm consider to use it in a package I'm building. I was wondering if there is a simple way to pass a nested array structure to process into header tags. I'm thinking of something like this:

```php
$data = [
    'title' => 'abc',
    'description' => 'bla bla...',

    'twitter' => [
        'card' => 'summary',
        'creator' => '@romanzipp'
    ]
];

// Rendering and returning the result
seo()->render($data);
```

Is this possible? 

Cheers,
Peter

**Comment by romanzipp** [comment]
That's a great idea which would open many more possibilites on how to manage the seo properties.

I'm currently struggeling on how to offer a fairly easy array syntax but preserving all possibilites on adding structs which are not included in shorthand setters ( `seo()->twitter()`, `seo()->title()` ).

My current draft in #22 proposes 3 different ways on how to add certain structs.

1. Single key-value pairs for title, description, charset...
2. Nested items like `['twitter' => ['card' => 'summary', 'creator' => '@romanzipp']]` for twitter & og. These will be unique and restricted since they are pretty much forwarding values to the twitter & og shorthand setters
3. Items for `<meta>` and `<link>` tags with nested `attribute => value` data

You can take a look at the new [ArrayFormatConductor](https://github.com/romanzipp/Laravel-SEO/blob/add-from-array/src/Conductors/ArrayFormatConductor.php#L30) or [unit test](https://github.com/romanzipp/Laravel-SEO/blob/add-from-array/tests/ArrayFormatTest.php) for more details.

What do you think of that approach?

### Example 

```php
seo()->addFromArray([

    'title' => 'Laravel',
    'description' => 'Laravel',

    'twitter' => [
        'card' => 'summary',
    ],

    'og' => [
        'locale' => 'de',
    ],

    'meta' => [
        [
            'name' => 'copyright',
            'content' => 'Roman Zipp',
        ],
    ],
]);
```

### Output

```html
<title>Laravel</title>
<meta property="og:title" content="Laravel" />
<meta name="twitter:title" content="Laravel" />

<meta name="description" content="Laravel" />
<meta property="og:description" content="Laravel" />
<meta name="twitter:description" content="Laravel" />

<meta name="twitter:card" content="summary" />
<meta property="og:locale" content="de" />

<meta name="copyright" content="Roman Zipp" />
```

**Comment by spekulatius** [comment]
Hey @romanzipp,

Awesome, this looks great and would get the job done! 

Do you think the PR is already ready to be merged or does it need more work?

Cheers,
Peter

**Comment by romanzipp** [comment]
I've tagged [version 2.1.0](https://github.com/romanzipp/Laravel-SEO/releases/tag/2.1.0) for this feature release!
