### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by martin-ro** [romanzipp/Laravel-SEO#44]
**Describe the bug**
Not sure if this qualifies as a bug.
Some tags are rendered twice while others are overridden.

**To Reproduce**
1. Create `AddSeoDefaults` middleware
2. Add `seo()->title(config('app.name'));` to `AddSeoDefaults` as fallback title
3. In your controller or elsewhere add `seo()->title('Something else');`
4. Title is as expected "Something else"
5. Add `seo()->meta('robots', 'index, follow')` to `AddSeoDefaults` as fallback tag
6. In your controller or elsewhere add `seo()->meta('robots', 'noindex, nofollow')`
7. `<meta name="robots" content="index, follow">` AND `<meta name="robots" content="noindex, nofollow">` are rendered.

**Expected behavior**
All tags should only be rendered once and be rendered as they are called the last in the stack.

**Comment by romanzipp** [comment]
Unfortunately this is the expected behavior. We can not declare all meta tags unique by identifing it's unique characteristics by the `name="..."` attribute since meta tags like OpenGraph use a `property="..."` instead of `name="..."`.

I've used the opportunity and added a new `Robots` struct which could be handy since it's frequently used.
This struct is unique across all other elements.

**Comment by martin-ro** [comment]
That's working with the struct, thanks!
